### ISSUE TITLE
Can't split logs in multiple files

### ISSUE THREAD

**Issue by rayko92** [homeaway/pino-rotating-file#3]
Hi, I tried to split logs into multiple files and doesn't work.

How does it work exactly?

The request.log contains all request generated. (request(info tag) and error tag)

.request-log.js
```
module.exports = {
    filter(data) {return data.req},
	output: {
		path: "request.log", // name of file
		options: {
			path: "./Logs/", // path to write files to
			size: "10M", // max file size
			rotate: 5, // keep 5 rotated logs
			compress: "gzip" // compress rotated files
		}
	}
}
```

.error-log.js
```
module.exports = {
    filter(data) {return data.req},
	output: {
		path: "error.log", // name of file
		options: {
			path: "./Logs/", // path to write files to
			size: "1M", // max file size
			rotate: 5, // keep 5 rotated logs
			compress: "gzip" // compress rotated files
		}
	}
}
```

example.js
```
server.log(['info'], 'Server running on %s', server.info.uri);
server.log(['error'], err);
```

Init
`node /example.js | rotate-logs --config=.request-log.js | rotate-logs --config=.error-log.js`

**Comment by qswitcher** [comment]
This is because your filter function is including all request logs, which can and will include error logs as well
```
    filter(data) {return data.req},
```
You'll need to refine that if you want just non-errors in `request.log`, something like
```
    filter(data) {return data.req && !data.err},
```
and in your .error-log.js config something like
```
    filter(data) {return data.err},
```

**Comment by beatgates** [comment]
Just wonder if you could also update the readme so that people will not be confused in the future?

In my case, I just use `filter(data) { return true }` to log everything.

**Comment by rayko92** [comment]
Thanks @qswitcher :)

**Comment by joonastanner** [comment]
Looks like this issue was resolved - thank you @qswitcher !
